"""Add name and hashed_password to users table

Revision ID: 9479400d8636
Revises: 001
Create Date: 2026-01-08 16:23:23.223086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9479400d8636'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playing_with_neon')

    # Add columns as nullable first
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))

    # Update existing rows with default values
    op.execute("UPDATE users SET name = 'Legacy User' WHERE name IS NULL")
    op.execute("UPDATE users SET hashed_password = 'invalid_hash' WHERE hashed_password IS NULL")

    # Make columns NOT NULL
    op.alter_column('users', 'name', nullable=False)
    op.alter_column('users', 'hashed_password', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'name')
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    # ### end Alembic commands ###
